name: "CI: Install, Lint, Test, and Upload Coverage"

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: "Checkout repo"
      uses: actions/checkout@v4

    - name: "Set up Conda"
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: environment.yml
        environment-name: brainfusion-env
        python-version: 3.12

    - name: "Install brainfusion and test dependencies"
      shell: bash -l {0}
      run: |
        conda activate brainfusion-env
        pip install -e .[dev]
        pip install pytest pytest-cov codecov

    - name: "Debug: Show installed packages"
      shell: bash -l {0}
      run: |
        conda activate brainfusion-env
        pip list

    - name: "Lint with flake8"
      shell: bash -l {0}
      run: |
        conda activate brainfusion-env
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: "Run tests with coverage"
      shell: bash -l {0}
      run: |
        conda activate brainfusion-env
        pytest --cov=brainfusion --cov-report=xml

    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}  # Only needed for private repos
        files: ./coverage.xml
        flags: unittests
        name: codecov-ubuntu
